### ISSUE TITLE
Running Passport install during installation

### ISSUE THREAD

**Issue by vijaythecoder** [rashidlaasri/LaravelInstaller#106]
Thanks for the great package. 👍 
I am looking to add extra artisan command to the installation process, I couldn't find it anywhere. For eg `php artisan passport:install`

I tried hacking into package and in DatabaseManager.php I have added like following
```
try{
            Artisan::call('passport:install', ["--force"=> true], $outputLog);
            Artisan::call('migrate', ["--force"=> true], $outputLog);
        }
```
but I get the following error
`There are no commands defined in the "passport" namespace.`

**Comment by vijaythecoder** [comment]
Can someone answer this? not sure why it was closed. I tried the documentation too but couldn't find anything.

**Comment by RachidLaasri** [comment]
Hi,

Pull in the last version 4.0.1. 

I have just added an event that fires when the install is done `RachidLaasri\LaravelInstaller\Events\ LaravelInstallerFinished`. Create a listener for that and run whatever code you want to.

**Comment by vijaythecoder** [comment]
Thanks a lot for the reply, yeah its working. Now I have a problem when installing, it fires migration but it is not migrating vendor migrations.

**Comment by RachidLaasri** [comment]
Can you explain more?

**Comment by RachidLaasri** [comment]
I am closing this because it seems inactive. If you still facing the same issue, feel free to reopen it.

Thank you.

**Comment by alshoja** [comment]
since am new to laravel , can u please provide more detail about adding a listener to your event ??  i need the passport install to be executed at last ?? can anyone help ?

**Comment by rashidlaasri** [comment]
@alshoja 

Adding a listener after the installer finishes is very simple. Follow the instructions on the [Laravel documentations ](https://laravel.com/docs/5.8/events#registering-events-and-listeners) and listen for when this event is raised: `RachidLaasri\LaravelInstaller\Events\LaravelInstallerFinished`.

**Comment by alshoja** [comment]
I tried to create a listener and it was successful but the event is raised in the events folder that is in the vendor folder, so how could the listener catch the event raised from vendor section? and also I just put the passport artisan command in the constructor that is on the **LaravelInstallerFinished** class and it worked but I need it to be enabled in the listener folder on **App\listeners**,

**Comment by rashidlaasri** [comment]
Exactly, you should be able to listen for the event even if it’s inside the vendor folder.

Just put the full class namespace (like you did above) and attach your listener to it and it’ll work.

**Comment by alshoja** [comment]
Thank you so much for the package, it is very helpfull for easy installation, it could be better if you add validations for database credentials for connection check

**Comment by rashidlaasri** [comment]
I will have a look into that in the future. Thank you for the suggestion.

**Comment by alshoja** [comment]
No mention, can you please look into the issue **#176** because even am to getting the same error?
