### ISSUE TITLE
Laravel 5.6 crash when config package published

### ISSUE THREAD

**Issue by d8vjork** [rashidlaasri/LaravelInstaller#138]
```PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in ...Illuminate\Container\Container.php:767```

**Comment by joveice** [comment]
require this package.
publish files
run this
```
$ php artisan config:clear
$ php artisan config:cache
```
issue replicated

**Comment by pythondev1** [comment]
Issue Replicated....

**Comment by joveice** [comment]
@RachidLaasri I found the issue, you are using rule at [line 70](https://github.com/RachidLaasri/LaravelInstaller/blob/master/src/Config/installer.php#L70)
Remove that and the issue is gone.

**Comment by RachidLaasri** [comment]
I am closing this because it seems inactive. If you still facing the same issue, feel free to reopen it.

Thank you.

**Comment by thomsontochi** [comment]
please am having the issue . can we reopen it

**Comment by umer1o9** [comment]
same issue any other solution.

**Comment by Samuel-Bie** [comment]
For those still facing the same problem, what I solved for me was: remove all contents of the bootstrap/cache folder, and run the composer dump command

**Comment by umer1o9** [comment]
this is not working for me

**Comment by umer1o9** [comment]
more than one week still facing that error

**Comment by pythondev1** [comment]
What I actually  found on mine was that it was an error 500 causing the issue in one of the middleware scripts (syntax error).

**Comment by rashidlaasri** [comment]
@umer1o9 @pythondev1 Can you share more details please? What errors you get?

**Comment by deepak-vidhema-solution** [comment]
Hi ..

Please commen in bootstrap/app.php file $app values 
like 
 //$app->register(Bitnary\JsonPaginate\JsonPaginateServiceProvider:class); // Bitnary JsonPaginate for o Eloquent
/*$app->register(Spatie\JsonApiPaginate\JsonApiPaginateServiceProvider::class);
$app->withFacades();
$app->withEloquent();
$app->configure('json-api-paginate');*/
//$app->register(LaravelFCM\FCMServiceProvider::class);
and than save and run 


php artisan config:clear
php artisan config:cache 
composer dump-autoload

**Comment by nickogor** [comment]
Who still get this error

Check out your **.env** file. 
Most likely you have space somewhere in your configurations:

MAIL_FROM_NAME=James Smith
should be:
MAIL_FROM_NAME="James Smith"
just make sure you dont have a spaces on your configs values.

**Comment by pentacore** [comment]
Tried everything mentioned here, No spaces anywhere in my .env file

**Comment by shashenta** [comment]
Do

Delete all the files in bootstrap/cache folder.
try to load page again and it works.

Thanks again Smauelbie, I would never have figured this out without your comment saying what to do.

**Comment by anouares-sayid** [comment]
I had the same problem with DOMPDF for Laravel, commenting this line in `bootstrap/app.php`  solved the problem so far

`//$app->register(\Barryvdh\DomPDF\ServiceProvider::class);`

**Comment by hadrianus-dev** [comment]
> I had the same problem with DOMPDF for Laravel, commenting this line in `bootstrap/app.php` solved the problem so far
> 
> `//$app->register(\Barryvdh\DomPDF\ServiceProvider::class);`

yes, for me too, right, this
