### ISSUE TITLE
Add custom .env setting into form wizard

### ISSUE THREAD

**Issue by pork94** [rashidlaasri/LaravelInstaller#158]
A brilliant project!

I have a laravel project that requires a custom .env setting. How do i add it into Form wizard and set the settings there instead of through classic editor.

Many thanks!

**Comment by UksusoFF** [comment]
@pork94
After publishing views you can change it as you wish. Add new inputs and remove not used.

Then you need extend ```\RachidLaasri\LaravelInstaller\Helpers\EnvironmentManager```change ```saveFileWizard``` function.

And [bind your class](https://laravel.com/docs/master/container#binding):
```$this->app->bind(\RachidLaasri\LaravelInstaller\Helpers\EnvironmentManager::class, YourEnvironmentManager::class);```

**Comment by pork94** [comment]
@UksusoFF 
Thanks for the headsup. 
Pardon me as I am very new to laravel. This is my first project.

I do not understand the meaning of extending and binding my class.

I have publish my view by using this line.
`php artisan vendor:publish --tag=laravelinstaller`

Can you explain it more explicitly? 

Thanks!

**Comment by UksusoFF** [comment]
@pork94 
https://gist.github.com/davejamesmiller/bd857d9b0ac895df7604dd2e63b23afe

**Comment by mrahmadt** [comment]
Modifying `\RachidLaasri\LaravelInstaller\Helpers\EnvironmentManager` manually is not a good solution, because this will be overwritten every time we have a package update
