### ISSUE TITLE
route install 404

### ISSUE THREAD

**Issue by davisharry** [rashidlaasri/LaravelInstaller#161]
I followed the tutorial and everything went well.
but when i visit  localhost/install, it turns out 404. and I trird localhost/installer 403 forbidden.
And I am using laravel 5.5, I have no idea what's the problem.
I check the file route/web.php, it's empty.

**Comment by brainkode** [comment]
In your vhost put allowoverdrride all like this:
<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

Check your if you have mod_rewrite enabled in apache ex: sudo a2enmod rewrite. And .htaccess
