### ISSUE TITLE
redirect on first time installer

### ISSUE THREAD

**Issue by devv66** [rashidlaasri/LaravelInstaller#163]
is there a way to make redirect to 'install' route on first time installer? i try with checking pdo connection on appserviceprovider, but there's something i need that appserviceprovider can't handle

**Comment by RERE110** [comment]
Why not create a middleware that checks the presence of the installation file generate in the storage folder ? and redirect to /install if it is not present ?

**Comment by RERE110** [comment]
```
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Closure $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $filename = storage_path("installed");
        if (file_exists($filename)) {
            return $next($request);
            echo "Le fichier $filename existe.";
        } else {
            return redirect('/install');
        }
    }
```
