### ISSUE TITLE
Laravel installer Works on Windows but not on Linux

### ISSUE THREAD

**Issue by ofunneka** [rashidlaasri/LaravelInstaller#164]
The Laravel Installer works well on windows. But gives 404 not found error on Linux.
LaravelInstallerServiceProvider has $this->loadRoutesFrom(__DIR__.'/../Routes/web.php');
What else should I do

**Comment by prappo** [comment]
Did you find any solution?

**Comment by ofunneka** [comment]
None yet.

**Comment by eliyas5044** [comment]
Here is the process in linux, tested in *elementary os 5*
```bash
# update user group of laravel project folder
sudo chown -R $USER:www-data /var/www/html/laravel
# give folder permissions
sudo chmod -R 775 storage
sudo chmod -R 775 bootstrap/cache
```
Then go to `/install` route and follow the steps.

**Comment by eliyas5044** [comment]
@princejohnpeal sorry, don't have mac, so no way to test. btw, how you did, please explain.

**Comment by princejohnpeal** [comment]
> @princejohnpeal sorry, don't have mac, so no way to test. btw, how you did, please explain.

tried as you said. How do I fix this issue in shared hosting? Its not working on cpanel/shared hosting neither.

**Comment by eliyas5044** [comment]
sorry, i didn't try it in shared hosting. but i made my own package using this package and could run successfullly in shared hosting. you may try. [laravel-visual-installer](https://github.com/eliyas5044/laravel-visual-installer)
