### ISSUE TITLE
Route [welcome] not defined.

### ISSUE THREAD

**Issue by Shahriar-ahmmed** [rashidlaasri/LaravelInstaller#165]
Hi,
I follow everything and works fine but after env file  step shwos Symfony\Component\Debug\Exception\FatalErrorException: Trait 'Illuminate\Foundation\Events\Dispatchable' not found

**Comment by HDVinnie** [comment]
If your app is outside the default laravel routes shown here on fresh install.
https://github.com/laravel/laravel/blob/master/routes/web.php

Then you need to update this line here to be your default route
https://github.com/rashidlaasri/LaravelInstaller/blob/aecc341e20841ed85c844ddb4d59466fab86ad72/src/Config/installer.php#L111
