### ISSUE TITLE
LogicException Error with Laravel 5.7

### ISSUE THREAD

**Issue by TechTailor** [rashidlaasri/LaravelInstaller#166]
LogicException  : Your configuration files are not serializable.

```
at C:\xampp\htdocs\testapp\vendor\laravel\framework\src\Illuminate\Foundation\Console\ConfigCacheCommand.php:68

 64|             require $configPath;
 65|         } catch (Throwable $e) {
 66|             $this->files->delete($configPath);
 67|
 68|             throw new LogicException('Your configuration files are not serializable.', 0, $e);
 69|         }
 70|
 71|         $this->info('Configuration cached successfully!');
 72|     }

Exception trace:

1   Error::("Call to undefined method Illuminate\Validation\Rules\In::__set_state()")
  C:\xampp\htdocs\testapp\bootstrap\cache\config.php:435

2   require()
  C:\xampp\htdocs\testapp\vendor\laravel\framework\src\Illuminate\Foundation\Console\ConfigCacheCommand.php:64

Please use the argument -v to see more details.
```

**Comment by HDVinnie** [comment]
This package does indeed break the ability to use `php artisan config:cache` because the config file in this package is bad. Line 70 is the issue I believe. 

In the mean time you can visit your `bootstrap/cache` dir and delete the cached routes.php file an that will fix your issue. But if you run `php artisan config:cache` again then if will come back.

**Comment by TechTailor** [comment]
Thanks for the reply, Yeah I figured that Laravel is unable to config because it cannot cache and considers this -

```
'app_debug'             => [
                    'required',
                    Rule::in(['true', 'false']),
                ],
```
as bad practice. Removing that line fixed all the issues.

**Comment by elnurxf** [comment]
Update to:

`'app_debug'           => 'required|boolean',`

**Comment by KumarSunil007** [comment]
This is issue with `laravel/framework/src/Illuminate/Validation` package. 

Here inside `Rule` folder, we have class named `In` (file `In.php`)

It is missing function `__set_state` .

If you will add following function in this class,
`static public function __set_state($array = []){
		return 'boolean';
	}`

The problem will be resolved. Also, it is temporary solution ( **composer install/update command can remove your function**)
