### ISSUE TITLE
Argument 1 passed to RequirementsChecker::check() must be of the type array

### ISSUE THREAD

**Issue by freescout-helpdesk** [rashidlaasri/LaravelInstaller#170]
Laravel 5.5
LaravelInstaller 4.0.2

After I open /install and click "Check Requirements ", I get the following error:

> Argument 1 passed to RachidLaasri\LaravelInstaller\Helpers\RequirementsChecker::check() must be of the type array, null given, called in /vendor/rachidlaasri/laravel-installer/src/Controllers/RequirementsController.php on line 34

`/config/installer.php` file exists and has `requirements` section.

**Comment by freescout-helpdesk** [comment]
Clearing /bootstrap/cache helped.

**Comment by AlmisbahTS** [comment]
php artisan config:cache
