### ISSUE TITLE
.env file QUEUE_DRIVER & etc

### ISSUE THREAD

**Issue by elnurxf** [rashidlaasri/LaravelInstaller#180]
Checkout [changelog](https://github.com/laravel/laravel/blob/fbd3ad7bbb5e98c607f19f7c697552863363bde4/CHANGELOG.md#v5713-2018-11-07) there is upgrade for:

QUEUE_DRIVER -> QUEUE_CONNECTION
APP_LOG_LEVEL -> *REMOVED*

Maybe It's better to take an .env.example and work on it, rather than put your including APP_KEY, even if resets later.

**Comment by rashidlaasri** [comment]
@elnurxf - Fixed. Thank you.

**Comment by mrahmadt** [comment]
> 
> 
> @elnurxf - Fixed. Thank you.

Sorry, but what do you mean by fixed ?

https://github.com/rashidlaasri/LaravelInstaller/blob/3dec1d54669959a5bd46f0cdde22e3e8c0a59836/src/Helpers/EnvironmentManager.php#L102
