### ISSUE TITLE
compact(): Undefined variable: envConfig issue ?

### ISSUE THREAD

**Issue by gazi-dis** [rashidlaasri/LaravelInstaller#192]
please add '$envConfig = $this->EnvironmentManager->getEnvContent();'  EnvironmentController saveWizard method.

**Comment by rashidlaasri** [comment]
Can your PR that? Thanks @gazi-dis

**Comment by gazi-dis** [comment]
![Ek Açıklama 2020-03-25 180042](https://user-images.githubusercontent.com/55152249/77550809-945c2900-6ec2-11ea-81ba-06b3c2158a3b.png)
İf is there any validator fail issue installer forms, I take a undefined variable issue. Because yours package controller>EnvironmentController>saveWizard method>validator conditions return envConfig variable. But envConfig variable is not defined.

**Comment by pricop** [comment]
I can confirm this is an issue. And also the fix gazi-dis provided seem to be working. Any chances of getting this into an actual release?
