### ISSUE TITLE
app debug must be true or false

### ISSUE THREAD

**Issue by akgarg007** [rashidlaasri/LaravelInstaller#197]
Hi, I'm testing this Laravel installer on a Mac machine, don't the reason of the error.
But I'm posting the error as well as solution here.
This is an error of data type, we are aspecting app_debug to be boolean, but I received string . 
So, I fixed the issue by a changing the validation type from boolean to string of the app_debug variable.

![error-01](https://user-images.githubusercontent.com/13774747/82325228-7ad5ea00-99f8-11ea-8187-8f30d1dffdfb.png)
![error-02](https://user-images.githubusercontent.com/13774747/82325242-845f5200-99f8-11ea-88ae-91aeb9a59303.png)
![error-03](https://user-images.githubusercontent.com/13774747/82325254-8d502380-99f8-11ea-9522-8a87be2ea577.png)

This is the solution:- Hope you will manage it.
![Solution](https://user-images.githubusercontent.com/13774747/82325282-9b05a900-99f8-11ea-96d2-ebeaddc9fea6.png)

**Comment by rashidlaasri** [comment]
Fixed: https://github.com/rashidlaasri/LaravelInstaller/pull/198
