### ISSUE TITLE
Install Not Found, redirect to 404 page

### ISSUE THREAD

**Issue by akgarg007** [rashidlaasri/LaravelInstaller#203]
I'm trying to use Laravel Installer in a project. I have cleared all the data and history from the project.
Ran `composer dump-autoload` and  `artisan optimize:clear` commands too.
Even deleted the Installer file from the Storage folder, which Installer creates previously, still its giving 404 error, when I visit install route.
Am I missing something?

**Comment by satorigold** [comment]
Yes just change the "example.htaccess" to .htaccess

**Comment by akgarg007** [comment]
Fixed, I was having some issues in the web middleware from my side. Thanks for the info.

**Comment by waqarali0911** [comment]
Hi i am facing same issue please can you  tell me how you sorted ?

**Comment by akgarg007** [comment]
What is your status regarding the plugin? Have you delete the Storage/Installed file?

**Comment by waqarali0911** [comment]
yes issue is i am not redirecting to install page... its give me general error access  denied for user@localhost mean its not detecting package install url

**Comment by akgarg007** [comment]
Looks like your web route middleware is asking for database, even without loggedIn, are you running any db query on the frontend?

**Comment by waqarali0911** [comment]
yes loading about us text and other from db on hompage

**Comment by akgarg007** [comment]
The purpose of the "LaravelInstaller" is to install the complete Laravel website including database too. So, don't use any database query on web middleware. Your "/" home route should not call any database query, before running the Laravel Installer. Hope you get my point.
