### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))

### ISSUE THREAD

**Issue by WrenchX** [rashidlaasri/LaravelInstaller#210]
I get this message after doing the migrations, I’m aware this is a limit configurable by the host, but I want to be able to install my software even with this limitation.

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))

**Comment by oranges13** [comment]
I've seen this in normal laravel apps too. Usually you can fix this in your application by setting the key length in your `AppServiceProvider.php` file: https://laravel-news.com/laravel-5-4-key-too-long-error
