### ISSUE TITLE
Error : Trying to access array offset on value of type int 

### ISSUE THREAD

**Issue by abhitheawesomecoder** [rashidlaasri/LaravelInstaller#211]
Error : Trying to access array offset on value of type int 

In PHP 7.4

**Comment by oranges13** [comment]
Which version of Laravel are you using?

**Comment by abhitheawesomecoder** [comment]
Laravel 5.6

**Comment by oranges13** [comment]
I have had this same error on versions of laravel <6 when running `artisan migrate` on PHP 7.4

Need to do more testing but I'm not sure 5.6 is compatible with PHP 7.4
