### ISSUE TITLE
Not found css file

### ISSUE THREAD

**Issue by Selembung** [rashidlaasri/LaravelInstaller#213]
View http://127.0.0.1:8000/install without css, why?

**Comment by oranges13** [comment]
Without more information it will be difficult to discern exactly why this is happening. But at first blush I would guess it's possibly a permissions error. Is the laravel folder accessible by the user running your website (apache, etc)

It would help if you had server logs or at least errors from chrome that can explain what's going on with the CSS.

**Comment by Selembung** [comment]
I just found a solution, so the master.blade.php file looks like it's not saved, because I see in the tab, the file name is italic, so then I try to save it with ctrl + s, and it turns out that the css file just reads.
