### ISSUE TITLE
'ioncube_loader' Requirement Not Working

### ISSUE THREAD

**Issue by s1rwan** [rashidlaasri/LaravelInstaller#214]
Hi guys,
I Want to add "ionCube" in Requirements Section.
How can I do this? @rashidlaasri 

I have added 'ioncube' in 'requirements' section, But when this extension is active, it also shows the error of not installing!

`'requirements' => [
        'php' => [
            'openssl',
            'pdo',
            'ioncube',
            'mbstring',
            'tokenizer',
            'JSON',
            'cURL',
            'xml',
            'ctype',
        ],
    ],`

![dfg](https://user-images.githubusercontent.com/60171454/105825757-33671b00-5fd5-11eb-877a-c262a7d24002.PNG)

**Comment by oranges13** [comment]
I think you may be misunderstanding the requirements section.

This does not install anything for you, it just means that whatever server they're attempting to install it on needs to have that extension enabled.

You have to install that extension manually and then it will meet the requirements that the installer is asking for.

You should also double check that the name is exactly as it's listed in the php.ini

**Comment by s1rwan** [comment]
@oranges13 ,
I think you misunderstood what I mean, I have already installed ionCube module on the server, but in the requirements check, it shows the message not to install by mistake.

`zend_extension = "C:\xampp\php\ext\ioncube_loader_win_7.4.dll"`

I guess I have to enter its name correctly in the requirements section, but I have tried many names (Like: ioncube, ioncube_loader, etc.. ) and none of them worked.

**Comment by rashidlaasri** [comment]
@s1rwan try `ionCube Loader` instead of `ioncube `

**Comment by oranges13** [comment]
If you do `php -m` is it listed there?

**Comment by s1rwan** [comment]
@rashidlaasri , 
It worked. thank you

**Comment by rashidlaasri** [comment]
Don't forget to donate some trees if this package helped you in some way.

https://github.com/rashidlaasri/LaravelInstaller#treeware
