### ISSUE TITLE
How to run Factory and Seeders.

### ISSUE THREAD

**Issue by BeycanDeveloper** [rashidlaasri/LaravelInstaller#232]
Hello, your package is very beautiful and useful. But for example I have Factory to add default settings and user after installation. I also added seeder but it doesn't work.

**Comment by rashidlaasri** [comment]
When the installation reaches its final step, we fire `LaravelInstallerFinished` event, you can listen for that and do any other setup you want. 

https://github.com/rashidlaasri/LaravelInstaller/blob/master/src/Controllers/FinalController.php#L27

**Comment by BeycanDeveloper** [comment]
Thank you. I am just learning Laravel. When I looked at the source code, I saw it and used it, thanks.
